spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: query-service
          uri: lb://QUERY-SERVICE
          predicates:
            - Path=/query/**
          filters:
            - name: CircuitBreaker
              args:
                name: queryCircuitBreaker
                fallbackUri: forward:/queryFallBack
        - id: command-service
          uri: lb://COMMAND-SERVICE
          predicates:
            - Path=/command/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8080